### ISSUE TITLE
if include story download option doesn't work

### ISSUE THREAD

**Issue by Purecoder** [fattynoparents/Batch-Media-Saver-for-Instagram#1]
Hi,

This extension awasome ! But when i select in setting menu "Include Stories" option doesn't work download process.
With comment work. :)

**Comment by fattynoparents** [comment]
Fixed this in version 4.1. Thanks for reporting the bug!

**Comment by Purecoder** [comment]
> 
> 
> Fixed this in version 4.1. Thanks for reporting the bug!

Thanks now work !
